### ISSUE TITLE
你好，大佬，请问能帮我加入wireguard,nps 内网穿透客户端，和adguard Home吗？

### ISSUE THREAD

**Issue by Gangnamsstyle** [mingcz0301/GL.iNET-B1300#1]
请问能帮我编译下这个路由器的固件，加入wireguard,nps 内网穿透客户端，和adguard Home吗？谢谢。

**Comment by mingcz0301** [comment]
可以考虑加入这么多东西
但是 Adguard Home  18M左右,upx 压缩就10M了, 装不下 路由器直接会挂的

**Comment by Gangnamsstyle** [comment]
![Screenshot 2021-11-11 142343](https://user-images.githubusercontent.com/69400033/141248478-ff1f42c2-87cb-468a-8015-2d0c00d18a91.png)
我就要这个打勾的，其他都不需要，然后再加上我刚才说的那几个，够吗？万一不行的话，adgaurd Home不加也行。

**Comment by Gangnamsstyle** [comment]
大佬，能帮助一下吗？谢谢

**Comment by mingcz0301** [comment]
晚上编译个看看

**Comment by mingcz0301** [comment]
branch  ISSUES1
