### ISSUE TITLE
你好，大佬，这款路由器能否帮我编译一个固件。

### ISSUE THREAD

**Issue by Gangnamsstyle** [mingcz0301/GL.iNET-B1300#2]
需要如下插件：wireguard
                         ShadowSocksR Plus+
                         Nps 内网穿透
                        MWAN3
                        MWAN3分流助手（mwan3helper)
  非常感谢！

**Comment by mingcz0301** [comment]
最新的固件里面应该有的呀。

**Comment by mingcz0301** [comment]
<img width="215" alt="image" src="https://user-images.githubusercontent.com/33192620/159196434-a74c8db8-0d42-4dd5-a38e-18f322876acc.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/33192620/159196453-d261f585-8cb4-41ba-80d4-fa419a1c324e.png">

**Comment by Gangnamsstyle** [comment]
好的，非常感谢！
